apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fkfuapr0a-nodejs 
  janus-idp.io/tekton: fkfuapr0a-nodejs
  backstage.io/kubernetes-id: fkfuapr0a-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fkfuapr0a-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml