apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fkfuapr0a-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-e0e6300df7.3nk2.p3.openshiftapps.com/rhtap/rhtap-qe:d8d533b78669bd456eeeb91909a1dfd4c01f611a@sha256:ef44b318c3c09d2b9dd643c891e4e7d29ff1c9bf01fc64641874fcc56e6c0ca5
          name: container-image
